export const WISHLIST_PRIORITY = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  URGENT: 4,
}

export const WISHLIST_PRIORITY_VALUES = Object.values(WISHLIST_PRIORITY)

export const WISHLIST_PRIORITY_LABELS = {
  [WISHLIST_PRIORITY.LOW]: 'Baixa',
  [WISHLIST_PRIORITY.MEDIUM]: 'Média',
  [WISHLIST_PRIORITY.HIGH]: 'Alta',
  [WISHLIST_PRIORITY.URGENT]: 'Urgente',
}

export const WISHLIST_PRIORITY_DESCRIPTIONS = {
  [WISHLIST_PRIORITY.LOW]: 'Baixa prioridade',
  [WISHLIST_PRIORITY.MEDIUM]: 'Média prioridade',
  [WISHLIST_PRIORITY.HIGH]: 'Alta prioridade',
  [WISHLIST_PRIORITY.URGENT]: 'Urgente prioridade',
}

export const WISHLIST_PRIORITY_COLORS = {
  [WISHLIST_PRIORITY.LOW]: '#10b981',
  [WISHLIST_PRIORITY.MEDIUM]: '#f59e0b',
  [WISHLIST_PRIORITY.HIGH]: '#ef4444',
  [WISHLIST_PRIORITY.URGENT]: '#a855f7',
}

export const WISHLIST_PRIORITY_OPTIONS = [
  { value: WISHLIST_PRIORITY.LOW, label: WISHLIST_PRIORITY_LABELS[WISHLIST_PRIORITY.LOW], color: WISHLIST_PRIORITY_COLORS[WISHLIST_PRIORITY.LOW] },
  { value: WISHLIST_PRIORITY.MEDIUM, label: WISHLIST_PRIORITY_LABELS[WISHLIST_PRIORITY.MEDIUM], color: WISHLIST_PRIORITY_COLORS[WISHLIST_PRIORITY.MEDIUM] },
  { value: WISHLIST_PRIORITY.HIGH, label: WISHLIST_PRIORITY_LABELS[WISHLIST_PRIORITY.HIGH], color: WISHLIST_PRIORITY_COLORS[WISHLIST_PRIORITY.HIGH] },
  { value: WISHLIST_PRIORITY.URGENT, label: WISHLIST_PRIORITY_LABELS[WISHLIST_PRIORITY.URGENT], color: WISHLIST_PRIORITY_COLORS[WISHLIST_PRIORITY.URGENT] },
]

export const WISHLIST_PRIORITY_FULL_LABELS = {
  [WISHLIST_PRIORITY.LOW]: 'Baixa prioridade',
  [WISHLIST_PRIORITY.MEDIUM]: 'Média prioridade',
  [WISHLIST_PRIORITY.HIGH]: 'Alta prioridade',
  [WISHLIST_PRIORITY.URGENT]: 'Urgente prioridade',
}
